let textos = {
  "P1A" : "(1988) Una explosión masiva destruye la ciudad de Tokio en un abrir y cerrar de ojos. La causa sigue siendo un misterio, y el mundo entero queda en shock. En medio de las ruinas, nace una nueva era.",
  "P2A" : "(2019) Neo-Tokio surge de las cenizas, una ciudad dominada por la violencia y el caos. Pandillas de motociclistas recorren sus calles, mientras el gobierno se hunde en la corrupción. La esperanza parece haber desaparecido.",
  "P3A" : "Kaneda, el líder de una pandilla juvenil, desafía el orden establecido con su grupo de motociclistas. Los enfrentamientos con otras pandillas son cada vez más intensos. La ciudad es un campo de batalla.",
  "P4A" : "Tetsuo, en medio de una persecucion, choca contra un misterioso niño de apariencia extraña, Takashi. Este encuentro desencadena eventos que transformarán su destino. Kaneda observa impotente.",
  "P5A" : "Tetsuo capturado por el gobierno y es retenido en un laboratorio secreto. Allí, comienzan a realizarle crueles experimentos. Pero algo despierta en su interior, un poder inmenso y peligroso.",
  "P6A" : "Kaneda: 'No voy a dejar que jueguen con mi amigo. ¡Tetsuo, aguanta!' Kaneda, impulsivo como siempre, se lanza al rescate. Sin embargo, el gobierno tiene otros planes, Kaneda es arrestado.",
  "P7A" : "Kaneda es liberado ya que no pertence a ningun grupo revolucionario, pero en la prision conoce a Kei, una chica de un grupo rebelde, y logra convencer a los policias que ella es parte de su pandilla.",
  "P8A" : "Kaneda: 'No puedo hacer esto solo. Necesito ayuda.'                                    Kei: 'Si Tetsuo sigue por ese camino, no quedará nada de él ni de nosotros.' Juntos, Kaneda y Kei se infiltran en las instalaciones del gobierno.",
  "P9A" : "En lo profundo de los archivos del gobierno, Kaneda descubre la verdad. Akira, una fuerza inconmensurable, yace dormida bajo la ciudad. Con un cañón láser en mano, Kaneda se prepara para la batalla final.",
  "P10A" : "Akira no es solo una leyenda, sino una realidad devastadora. El gobierno ha estado jugando con fuego. Kaneda sabe que el tiempo se agota. Tetsuo ya no es el mismo. Su poder ha superado todo control, incluso el suyo propio. Kaneda se da cuenta de que quizas no pueda salvarlo.",
  "P6B" : "Tetsuo: '¡Todo este poder...! ¿Qué me está pasando?' El cuerpo y la mente de Tetsuo comienzan a fracturarse bajo la presión de sus nuevos dones. La rabia y el deseo de venganza lo consumen.",
  "P7B" : "Los experimentos han desatado el verdadero poder de Tetsuo. Pero con cada paso que da, pierde más control sobre sí mismo. Se convierte en una bomba de tiempo.",
  "P8B" : "Tetsuo: '¿Akira... quién es él? Necesito saber... ¡Lo necesito ahora!' En su búsqueda por respuestas, Tetsuo se obsesiona con encontrar a Akira. Su camino lo llevará al centro de un poder inimaginable.",
  "F1A" : "Tetsuo finalmente llega a la cámara subterránea y despierta a Akira. Kaneda llega demasiado tarde como para detenerlo. El equilibrio de Neo-Tokio está al borde del colapso. El destino de la ciudad está en sus manos.",
  "F2A" : "Tetsuo absorbe a Akira y desata todo su poder, pero es incapaz de controlarlo. La energía psíquica de Akira inunda la ciudad. Todo comienza a desmoronarse en una catástrofe imparable. Kaneda toma la difícil decisión de enfrentar a su amigo por última vez.",
  "F3A" : "Con la ayuda de los niños psíquicos, Kaneda logra detener a Tetsuo. Aunque Neo-Tokio ha quedado devastada, hay un atisbo de esperanza para el futuro. La ciudad puede ser reconstruida.",
  "F3B" : "Tetsuo se convierte en una entidad superior, dejando atrás la humanidad.  Neo-Tokio se derrumba bajo la inmensa presión de su poder. Pero Tetsuo continúa, ahora como una fuerza cósmica más allá de la comprensión. Su legado perdurará en otro plano de la realidad.",
  "F2C" : "Tetsuo intenta usar el poder de Akira para sus propios fines, pero se arriesga a perderlo todo. El poder de Akira es más grande de lo que Tetsuo puede manejar. Él lo sabe, pero el orgullo lo empuja a seguir. El precio a pagar será alto.",
  "F3C" : "En un momento de claridad, Tetsuo toma una última decisión heroica. Tetsuo se sacrifica para contener la energía de Akira. Aunque muere, su sacrificio permite que la ciudad sobreviva. Kaneda lo recuerda con tristeza, sabiendo que su amigo fue un héroe en sus últimos momentos.",
}

let pantallas = {
  "Inicio" : ["P1A"],
  "P1A" : ["P2A"],
  "P2A" : ["P3A"],
  "P3A" : ["P4A"],
  "P4A" : ["P5A"],
  "P5A" : ["P6A", "P6B"],
  "P6A" : ["P7A"],
  "P7A" : ["P8A"],
  "P8A" : ["P9A"],
  "P9A" : ["P10A"],
  "P10A" : ["F1A"],
  "P6B" : ["P7B"],
  "P7B" : ["P8B"],
  "P8B" : ["F1A"],
  "F1A" : ["F2A", "F2C"],
  "F2A" : ["F3A", "F3B"],
  "F2C" : ["F3C"],
  "F3A" : ["Creditos"],
  "F3B" : ["Creditos"],
  "F3C" : ["Creditos"],
  "Creditos" : ["Inicio"]
}

let botones = {
  "Inicio" : ["Jugar"],
  "P1A" : ["Continuar"],
  "P2A" : ["Continuar"],
  "P3A" : ["Continuar"],
  "P4A" : ["Continuar"],
  "P5A" : ["Kaneda", "Tetsuo"],
  "P6A" : ["Continuar"],
  "P7A" : ["Continuar"],
  "P8A" : ["Continuar"],
  "P9A" : ["Continuar"],
  "P10A" : ["Continuar"],
  "P6B" : ["Continuar"],
  "P7B" : ["Continuar"],
  "P8B" : ["Continuar"],
  "F1A" : ["Sí", "No"],
  "F2A" : ["Sí", "No"],
  "F2C" : ["Continuar"],
  "F3A" : ["Creditos"],
  "F3B" : ["Creditos"],
  "F3C" : ["Creditos"],
  "Creditos" : ["Volver a Empezar"]
}

let informacion = {
  "P5A" : ["Decisión: ¿Seguir la perspectiva de Kaneda o la de Tetsuo?"],
  "F1A" : ["Decisión: ¿Luchar contra Akira?"],
  "F2A" : ["Decisión: ¿Intentar detener a Tetsuo?"],
  "F3A" : ["Final N°1: Esperanza"],
  "F3B" : ["Final N°2: Trascendente"],
  "F3C" : ["Final N°3: Sacrificio"],
}

let imagenes = {
  "Inicio" : "escena1",
  "P1A" : "escena2",
  "P2A" : "escena3",
  "P3A" : "escena4",
  "P4A" : "escena5",
  "P5A" : "escena6",
  "P6A" : "escena7",
  "P7A" : "escena8",
  "P8A" : "escena9",
  "P9A" : "escena10",
  "P10A" : "escena11",
  "P6B" : "escena12",
  "P7B" : "escena13",
  "P8B" : "escena14",
  "F1A" : "escena15",
  "F2A" : "escena16",
  "F2C" : "escena17",
  "F3A" : "escena18",
  "F3B" : "escena19",
  "F3C" : "escena20",
  "Creditos" : "escena21"
}
